baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Python by example'
theme = "hugo-bearblog"

enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
  blog = "/:slug/"

[params]
    title = "Python by example"
    description = "Learn Python by example"
    hideMadeWithLine = true